name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build
    - name: List build directory
      run: ls -R ./build  # Adjust this based on your build output folder
    - name: Upload build artifacts (optional)
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./build  # Upload build artifacts for further inspection if needed
