version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22 # Specify the Node.js version
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build # Runs the React build process

  post_build:
    commands:
      - echo Build completed. Preparing for deployment...
      # Zip the build folder for deployment (optional)
      - zip -r build.zip build

artifacts:
  files:
    - '**/*' # Include all files in the build output
  base-directory: build # Directory where React build output is located

cache:
  paths:
    - node_modules/**/* # Cache dependencies to speed up build times
